# Generated by Django 4.1.2 on 2022-11-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.TextField(max_length=1000, null=True)),
                (
                    "uploadimage",
                    models.FileField(default=None, null=True, upload_to="news/"),
                ),
            ],
        ),
    ]
